### PR TITLE
Correct name for sudo file when is sudo granting for group

### PR DESCRIPTION
**Pull request by LesTR**
remove '%' from filename in sudo_sudoersd_dir for group

### CODE REVIEW

**Comment by groggemans** [comment]
Thank You for the PR!

Definitely want to add group support. Would you mind if I added it in a different way so it better incorporates with my other roles? Either (or both) by adding a group flag to the dict, or by a separate list for groups. 

I could still support/accept your solution, but in most cases you would have to define data several times to use it. So it doesn't seem a very good solution to the problem.

Comments and ideas welcome!

**Comment by LesTR** [comment]
For sure, i just wanna have support for groups. If it will be via another variable or other way doesn't matter. Do you wanna update this PR from me?

**Comment by groggemans** [comment]
Had a busy weekend, adding group support tomorrow!

**Comment by groggemans** [comment]
I've added group support with #13. I used a separate PR so we can reopen this one if someone would really like this approach.

**Pull request closed without merging**
